### PR TITLE
Make number of stripes configurable

### PR DESCRIPTION
**Pull request by jschmied**
The default numer of 16 is to low for real load.

### CODE REVIEW

**Comment by mojgh** [comment]
Meaningful enhancement. Thank you!

**Comment by Avinash-Bhat** [comment]
@mojgh will this be cherry-picked on branch 1.1?

**Comment by mojgh** [comment]
@Avinash-Bhat backport to branch version-1 is done (branch "1.1" is renamed to "version-1")

**Comment by mojgh** [comment]
Release notes: https://github.com/mojgh/JKeyLockManager#versions

**Pull request merged**
